### PR TITLE
Simplified Condition for Date/Time aliases

### PR DESCRIPTION
**Pull request by samtrion**
This means that future versions should also be automatically included.

### CODE REVIEW

**Comment by samtrion** [comment]
@SimonCropp What do you thing?

**Comment by SimonCropp** [comment]
isnt NETCoreSdkVersion incorrect? ie someone can use sdk9 and still target netclassic

**Comment by samtrion** [comment]
You are right, it is much more effective if $(TargetFrameworkVersion) is used. If `netclassic` is used.

**Comment by SimonCropp** [comment]
@samtrion so are you actually using this package?

**Comment by samtrion** [comment]
> @samtrion so are you actually using this package?

Had experimented with it once, but it didn't fulfil all the requirements / concerns, so no. During the experiment I came across to this pull request, unfortunately without looking at `netclassic`.

**Comment by SimonCropp** [comment]
> fulfil all the requirements / concerns

out of curiosity, how does your approach differ?

**Comment by samtrion** [comment]
I am currently refactoring, so far I had an [‘engineering’ repository](https://github.com/dailydevops/dotnet-engineering) as a git submodule. This provided the necessary properties, settings, etc. and the main disadvantage is that I can't integrate it cleanly into existing projects.

Unfortunately, this has increasingly led to complications or errors, as my aim is not only to make specifications, but also to check/validate them accordingly.

I have therefore extended the experiment and am currently starting a deeper phase with a combination of a `source only` NuGet package and a corresponding analyser. In other words, I'm gradually breaking down my `engineering` repo and transferring it to these packages. https://github.com/dailydevops/defaults

I do have a clear goal in mind to significantly reduce administration and maintenance effort for new and current projects, but not under all circumstances.

There are a few points in particular that I am focussing on for the experiment, for the start.

- Default NuGet package information
- Analyser for NuGet package information
- Mechanism to allow or disallow references to NuGet packages
- Shareable `.editorconfig`, can be partially deactivated via project properties
- Shareable configurations for banned API analyser, can also be deactivated for project properties

Other points are already on the todo list, but are not part of the ‘experiment’.

**Pull request merged**
